config/routes.rb
Rails.application.routes.draw do
  root to: "urls#index"

  post "/", to: "urls#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :urls
  resources :users

end

app/models/url.rb
class Url < ActiveRecord::Base
  before_create :shorten
  belongs_to :user

  validates :target, presence: true

  def shorten
    self.target = "http://" + target if target[0..3] != "http"
    self.chopped = get_short
  end

  def get_short
    len = %w(1 2 3 4)
    short = SecureRandom.hex(len.sample.to_i)
    get_short if Url.find_by(chopped: short)
    short
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :urls
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session[:user_id] = nil
  end
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      login user
      redirect_to root_path
    else
      flash["error"] = "Invalid email/password"
      redirect_to login_path
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def create
    @url = Url.new(url_params)
    @url.user = current_user
    if @url.save
      respond_to do |format|
        format.js
      end
    end
  end

  def index
    @url = Url.new
  end

  def url_params
    params.require(:url).permit(:target)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      login user
      redirect_to root_path
    else
      flash["errors"] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in_user
    current_user
  end

  def session_button
    if current_user
      render partial: "partials/logout_link"
    else
      render partial: "partials/session_buttons"
    end
  end

  def monitor_alert
    render partial: "partials/monitor_link" unless current_user
  end

  def dashboard
    render partial: "partials/dashboard_link" if current_user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login_successful(user)
    session[:user_id] = user.id
  end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chopp - Shorten your url</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="body-main">

<%= yield %>

</body>
</html>

app/views/partials/_dashboard_link.html.erb
<li><%= link_to "DAshboard", login_path %></li>

app/views/partials/_footer.html.erb
<div class="my-footer">
  <span class="pull-left">Copyright © 2016 AceGrid Media  </span>
   <span class="pull-right"><i class="fa fa-github g-logo" aria-hidden="true"></i> </span>
   <span class="pull-right"><i class="fa fa-globe g-logo" aria-hidden="true"></i> </span>
    <span class="pull-right"><i class="fa fa-twitter g-logo" aria-hidden="true"></i> </span>
</div>

app/views/partials/_header.html.erb
<div class="container cont-header">
  <nav class="navbar navbar-default navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> &nbsp; </li>
        <li><a href="#">About </a></li>
        <li><a href="https://github.com/andela-oosiname/chopp" target="blank">Github Page</a></li>
        <%= dashboard %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      <%= session_button %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/partials/_logout_link.html.erb
<li><%= link_to "Log Out", logout_path %></li>

app/views/partials/_monitor_link.html.erb
<div class="row">

  <div class="alert alert-info monitor">
    <span> <%= link_to "Sign Up", new_user_path %> or <%= link_to "Login", login_path %> to monitor your links </span>
  </div>

</div>

app/views/partials/_session_buttons.html.erb
 <li><%= link_to login_path do %><%= button_tag "LOGIN", class: "btn my-login" %><% end %> </li>
 <li><%= link_to new_user_path do %><%= button_tag "SIGN UP", class: "btn my-signup" %><% end %></li>

app/views/urls/_new.html.erb
 <%= form_for @url, remote: true, html: { style: "display:inline;" } do |f| %>

        <h2 class="error"></h2>
        <h2 id="errors"></h2>

        <div class="form-group">
          <%= f.label :target, class:"control-label" %>
          <%= f.text_field :target, class: "form-control" %>
        </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>

app/views/urls/create.js.erb
<% if @url.chopped %>
  $(".chopped").css("display", "block");
  $("#chopped").text("<%= request.base_url %>/<%= @url.chopped %>");
  $(".extlink").attr( "href" , "<%= @url.target %>" );
  $("#target").text("<%= @url.target %>");

<% else %>
  $(".chopped").css("display", "block");
  $("#target").text("An error occured");
<% end %>

app/views/urls/index.html.erb
<section class="main chop-section">
  <%= render partial: "partials/header" %>
  <div class="container box">
   <%= form_for @url, remote: true, html: { style: "display:inline;" } do |f| %>

   <h2 class="error"></h2>

    <div class="input-group">
      <%= f.text_field :target, class: "form-control chop", placeholder: "Paste Url Here .... ", required: "required" %>
      <span class="input-group-btn">
        <%= f.submit "CHOP", class: "btn chop-button" %>
      </span>
      <% end %>
    </div>
    <div class="chopped" id="chopped-div">
      <div class="row">

      <a href="" class="extlink" target="blank"><span id="chopped"></span></a>
       <button class='my_clip_button btn' data-clipboard-target='chopped' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button' title='Click here to copy link.'>
        <i class="fa fa-clipboard" aria-hidden="true"> copy</i>
        </button>
        <span id="copied" display="none">Copied!</span>
      </div>
      <%= monitor_alert %>
    </div>
  </div>
</section>
<%= render partial: "partials/footer" %>

app/views/urls/new.html.erb
<div class="main">
  <div class="container">
    <section id="chop" class="chop">

    </section>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-box">
  <%= form_for @user, html: { style: "display:inline;" } do |f| %>
      <h2 class="error"></h2>
      <div class="form-group">
        <%= f.text_field :username, class: "form-control user-input", placeholder: "Username "%>
      </div>
      <div class="form-group">
        <%= f.password_field :password, class: "form-control user-input", placeholder: "Password "%>
      </div>

      <div class="form-group">
        <%= f.submit "SUBMIT", class: "btn user-btn" %>
      </div>
  <% end %>
    <p>Already have an account? <%= link_to " Sign In", login_path %> </p>
</div>